server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://47.92.87.72:3306/jswl_info_publish?useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    livereload:
      enabled: true
      port: 35729
    restart:
      enabled: true

mybatis-plus:
  mapper-locations: classpath*:/**Mapper.xml
  type-aliases-package: com.example.demo.entity
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      table-underline: true
      capital-mode: true
      column-like: true
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.example.demo: debug
    org.springfromework.web: debug
  file: log\demo.log
